#!/bin/sh

CONFIG="${CONFIG:-/etc/npreal2d.cf}"
ttymajor=33
calloutmajor=38

rm -f /dev/ttyr* /dev/cur*
modprobe npreal2 ttymajor="$ttymajor" calloutmajor="$calloutmajor" verbose=0

grep -vE '#|^$|ttymajor|calloutmajor' $CONFIG |
while read minor server data cmd fifo ssl tty callout iface mode backup; do
	mknod -m 660 /dev/"$tty" c "$ttymajor" "$minor"
	mknod -m 660 /dev/"$callout" c "$calloutmajor" "$minor"
	chgrp dialout /dev/"$tty" /dev/"$callout"
done

